### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by oskarrough** [runspired/smoke-and-mirrors#1]
Hey, this is really exciting. I'm trying to follow some of your performance tips, you mention background loading, could you share a code example?

Would also be great to see one with Ember.run.schedule. I'm not sure which parts of my code could benefit from it.

**Comment by runspired** [comment]
@oskarrough thanks for the feedback!

I won't have time to write up either of these for a while, but adding optimization examples to the guide is definitely on my radar.

The way to approach using `Ember.run.schedule` is to think from a UI first perspective.

- Does the asynchronous task (perhaps an ajax call) need to happen before any UI updates that might be happening?  If not, use `Ember.run.schedule('afterRender', this, someFunction);`

- Is the synchronous task expensive to perform?  Could it happen asynchronously? Does it need to happen before a render?  If not, same solution, schedule it into `afterRender`.

**Comment by runspired** [comment]
A quick demo of somewhere I've done this to optimize the demo.

https://github.com/runspired/smoke-and-mirrors/blob/master/tests/dummy/app/resources/dbmon-occlusion-collection/route.js#L18-L24

The original (both Glimmer and the Ryan Florence example) used `setTimeout`.  The pattern in use allows me to adjust the timeout while also ensuring that the next (expensive) call to get data isn't made
until the last render cycle has completed.
