### ISSUE TITLE
Occlusion-collection occasionally skips rendering top item.

### ISSUE THREAD

**Issue by runspired** [runspired/smoke-and-mirrors#10]
Likely we need to add a few pixels to the test for the topmost or bottom most element as an error buffer.

**Comment by aquamme** [comment]
I've noticed this as well. Setting `invisibleBuffer=0` seems to prevent the issue from occurring.

**Comment by runspired** [comment]
The invisible buffer is actually the buffer you want to keep largest if you have a long list of small items.
  
In 0.2 beta I've added 1px to the top test and that seemed to fix the issue, I think the math was prone to missing the topmost view when the math on the height wasn't a perfect number.  Since this adjustment, I haven't bumped into this issue again.
