### ISSUE TITLE
Readme instructions for installation and usage?

### ISSUE THREAD

**Issue by andrewhavens** [runspired/smoke-and-mirrors#111]
Hi Chris,

I'm getting started with Ember CLI, so I'm pretty new to this. I noticed that there aren't any installation or setup instructions in the readme, nor on the website. Do I just run `ember install smoke-and-mirrors`?

It would probably help newcomers (like me) if there was a basic intro on how to install and set up (import?) the package and its services/components.

Thanks!

**Comment by runspired** [comment]
Closing as duplicate of #118
