### ISSUE TITLE
master fails to build with missing `loader` dependency

### ISSUE THREAD

**Issue by CodeOfficer** [runspired/smoke-and-mirrors#114]
I noticed the PR for https://github.com/runspired/smoke-and-mirrors/pull/110 was failing and was able to reproduce this locally on plain master. There appears to be something different about master and develop .... also worth mentioning that at this time develop is 0.5.1 while master is 0.5.2 .... missing commits in develop maybe? Master failed to build locally with the following error:

> Building
> Smoke-and-mirrors:: Including Vertical-Collection Debug CSS
> The loader.js addon is missing from your project, please add it to `package.json`.

**Comment by runspired** [comment]
Fixed.
