### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by andrejewski** [runspired/smoke-and-mirrors#118]
I would like to submit a PR for updating the documentation for S&M for either README docs (#111, etc) or the Github Pages site which appears to be still using pre-0.4.4 and 0.4.4 examples. I don't know if there are going to be new changes to the API that might put documentation on the back burner, let me know.

**Comment by runspired** [comment]
@andrejewski updated docs are 👍 

I'll be doing a 0.6 release I've decided with various improvements I've found while building out 1.0, there are immediate wins we can have now that are much simpler and easier to achieve than the large effort still required to land 1.0

**Comment by andrejewski** [comment]
So should we do docs for 0.6? How close do you expect the release date to be?

**Comment by runspired** [comment]
Do the docs for 0.6, release date is within 6 weeks
