### ISSUE TITLE
Transition from list to single then back to list removes scroll listener

### ISSUE THREAD

**Issue by dylanfoster** [runspired/smoke-and-mirrors#125]
At least that's what I believe is happening. Basically, on a list view, the scroll listener fires fine, then if you transition to single item, then back to the list, nothing is fired. I set a debugger in `VerticalCollection._updateChildStates` to verify and this seems to be completely skipped after coming back to the list

**Comment by runspired** [comment]
I observed what I think is this bug while working on updating the docs site, but it wasn't consistently reproducible. Will try to investigate this soon.

**Comment by dylanfoster** [comment]
Awesome let me know if I can help in any way

**Comment by runspired** [comment]
Should be fixed by updating to `@html-next/vertical-collection` (now re-exported by this lib)
