### ISSUE TITLE
CacheList issues

### ISSUE THREAD

**Issue by adamjmcgrath** [runspired/smoke-and-mirrors#130]
I noticed that when the number of items in `CacheList` hits `MAX_ARRAY_SIZE` `this._map` is not created when it should be

I also noticed that the `Map` should only be created once (currently it's created in the for loop, so `this._map` gets overridden)

I also noticed that `EmptyObject` doesn't have the same API as `Map`, so `this._map.get(...)` etc wont work if it falls back to `EmptyObject` (also `this._map.remove` should be `this._map.delete` for the `Map`)

https://github.com/runspired/smoke-and-mirrors/blob/develop/addon/-private/cache-list/index.js#L39

I suggest something like:

```
this._indeces[index] = key;
this._values[index] = value;

if (this.length !== MAX_ARRAY_SIZE) {
  return;
}

this._map = new Map(); // require babel polyfil?
for (let i = 0; i < MAX_ARRAY_SIZE; i++) {
  this._map.set(this._indeces[i], this._values[i]);
}
```

I'm not familiar with this type of optimization, but I can't figure out why you wouldn't just want a `Map` (notwithstanding babel/browser support), I guess the space complexity is reduced by the 2 arrays to the detriment of the time complexity (I assume `arrayA[arrayB.indexOf(key)]` is slower than `map.get(key)` but `map` takes up more memory than `array`). 

This may be work in progress for you, but happy to raise a PR for the suggested fixes if you agree.

**Comment by runspired** [comment]
This was work-in-progress based on some low level perf investigations.  The work is moving into a separate lib and a different approach is going to be used here.  Thanks for spotting these things though :)
