### ISSUE TITLE
Error when running scrollable body example this.element.getBoundingClientRect is not a function

### ISSUE THREAD

**Issue by shishirmk** [runspired/smoke-and-mirrors#131]
I just downloaded the develop branch. I tried the dummy app. I see an error when i try the `scrollable body` example. 

Here is the screenshot of the error backtrace
![screen shot 2016-08-18 at 5 40 14 pm](https://cloud.githubusercontent.com/assets/604135/17795255/af3bc564-656b-11e6-92f2-0286fccbdb58.png)

**Comment by shishirmk** [comment]
Added a pull request for this #132

**Comment by oligriffiths** [comment]
+1 seeing this too

**Comment by runspired** [comment]
Resolved in 0.5.5

**Comment by shishirmk** [comment]
@runspired  Thank you for sharing that its fixed
