### ISSUE TITLE
Vertical Collection when collection starts off screen

### ISSUE THREAD

**Issue by kylemellander** [runspired/smoke-and-mirrors#150]
### Description

When loading a vertical collection below the current viewport (because of content that shares the container), it will error and either not load or act erratically.

### Replication

* Create content in your container that has a height greater than your current viewport
* Load in a vertical collection below it so that it initially renders below the viewable screen
* An error comes saying: ```EmberErrordescription: undefinedfileName: undefinedlineNumber: undefinedmessage: "Assertion Failed: Cannot call get with 'content' on an undefined object."name: "Error"number: undefinedstack: "Error: Assertion Failed: Cannot call get with 'content' on an undefined object.↵    at EmberError (http://localhost:4202/assets/vendor-139b691a0d6e91ebb90fd317c25ea241.js:33847:21)↵    at assert (http://localhost:4202/assets/vendor-139b691a0d6e91ebb90fd317c25ea241.js:21545:13)↵    at Object.assert (http://localhost:4202/assets/vendor-139b691a0d6e91ebb90fd317c25ea241.js:33659:34)↵    at get (http://localhost:4202/assets/vendor-139b691a0d6e91ebb90fd317c25ea241.js:38170:22)↵    at getContent (http://localhost:4202/assets/vendor-139b691a0d6e91ebb90fd317c25ea241.js:196520:12)↵    at Class.prepareActionContext (http://localhost:4202/assets/vendor-139b691a0d6e91ebb90fd317c25ea241.js:196802:22)↵    at Class.sendActionOnce (http://localhost:4202/assets/vendor-139b691a0d6e91ebb90fd317c25ea241.js:196818:22)↵    at Class._updateChildStates (http://localhost:4202/assets/vendor-139b691a0d6e91ebb90fd317c25ea241.js:197017:12)↵    at http://localhost:4202/assets/vendor-139b691a0d6e91ebb90fd317c25ea241.js:197050:18↵    at execJob (http://localhost:4202/assets/vendor-139b691a0d6e91ebb90fd317c25ea241.js:195977:9)"__proto__: Errorassert @ ember.debug.js:6778assert @ ember.debug.js:18892get @ ember.debug.js:23403getContent @ component.js:20prepareActionContext @ component.js:302sendActionOnce @ component.js:318_updateChildStates @ component.js:517(anonymous function) @ component.js:550execJob @ index.js:28invoke @ ember.debug.js:990flush @ ember.debug.js:1054flush @ ember.debug.js:862end @ ember.debug.js:176run.end @ ember.debug.js:23873flush @ index.js:101(anonymous function) @ index.js:70```

**Comment by runspired** [comment]
Should be fixed by updating to `@html-next/vertical-collection` (now re-exported by this lib)
