### ISSUE TITLE
How to get elementId from firstVisibleChanged data?

### ISSUE THREAD

**Issue by daniel-de-wit** [runspired/smoke-and-mirrors#154]
First of all, thank you for such an excellent performing addon, a true life saver for me.

In my app I'm trying to persist the scroll position of a vertical-collection when scrolling.
The content for the `vertical-collection` is stored in a service so that when the user returns to the page the content is still loaded. Now I would like to scroll to the position where he/she left off.

My idea was to use the `firstVisibleChanged` action to keep track of the current item in view.
`firstVisibleChanged` returns an object like:
![image](https://cloud.githubusercontent.com/assets/3015394/22112766/83d79ad4-de64-11e6-8e5f-06fadfe20114.png)

Which is great, because I get information on the actual record being used to show this item.
But it's unclear to me how to get the following value out of it since I can't predict the key:
![image](https://cloud.githubusercontent.com/assets/3015394/22113135/98bcf394-de65-11e6-9f64-e78c4846dd70.png)
I need `"ember1026"` to set `idForFirstItem` when re-rendering the `vertical-collection`.
Any ideas?

**Comment by runspired** [comment]
@daniel-de-wit you can set `key` to `id` in this case, although I see your point and think we should expose the key.

**Comment by runspired** [comment]
Fixed upstream.
