### ISSUE TITLE
Deprecation warning about Ember.K after upgrading to Ember v2.12.1

### ISSUE THREAD

**Issue by localpcguy** [runspired/smoke-and-mirrors#159]
Got the following deprecation notice after upgrading Ember to v2.12.1 (from v2.9.x). If this is relatively simple, I'm happy to submit a PR to remove it. Looks like it could just be replaced with either `function() { }` or `function() { return this; }`?

DEPRECATION: `Ember.K` is deprecated in favor of defining a function inline. [deprecation id: ember-metal.ember-k]

https://emberjs.com/deprecations/v2.x/#toc_code-ember-k-code

Defined here: https://github.com/runspired/smoke-and-mirrors/blob/develop/addon/components/vertical-collection/component.js#L13
Used here: https://github.com/runspired/smoke-and-mirrors/blob/develop/addon/components/vertical-collection/component.js#L282

**Comment by rafael-paiva** [comment]
+1

**Comment by rafael-paiva** [comment]
Is this repo still maintained? This is a simple change that has been sitting here for 4 months. It's really annoying to see these deprecation warnings.

**Comment by localpcguy** [comment]
My understanding is that work is ongoing on a different repo, I think(?) the following link, and that's where the maintainers are focused. I'm sure a PR would be acceptable, and I just keep forgetting to submit it when I have time.

https://github.com/html-next/vertical-collection

**Comment by rafael-paiva** [comment]
Ah, I keep forgetting the repo moved. I tried moving to this new repo once, I was spending too much time getting it to work properly and I didn't have much time then. Thanks! I'll try again eventually :)
