### ISSUE TITLE
Non-CLI project Support

### ISSUE THREAD

**Issue by bsouid** [runspired/smoke-and-mirrors#16]
Is there any way to use this in a non-CLI project? 

I am fairly new to the Ember and cant use CLI for requirements reasons. There doesnt appear to be much in the way of doing cloaking in "regular" Ember projects.

**Comment by runspired** [comment]
What sort of requirement prevents you from using ember-cli? It's inter-workable with any other existing build system.  I won't be providing a globals build, as globals based versions of addons lack proper configurability.

There is a way to use this in non-cli projects, but that too is experimental: https://github.com/ef4/ember-giftwrap

**Comment by bsouid** [comment]
@runspired Thank you so much for the quick reply. 

The reason I havent gone to CLI is because of human issues not because of technical issues: I am the only web developer building on-top of their existing ASP.NET project (which they still need to be able to modify themselves sometimes). The idea of getting a bunch of .NET devs to sign-off on a new build system that is not CTRL-B in Visual Studio is going to be a no go for a while. Especially since all the rolling agents use MSBUILD. Sigh. Working on the Microsoft platform always gives weird challenges.

Anyway I understand that it is not worth shipping a globals version if there is not enough demand. Thank you for all of your hard work and for the suggested work around.
