### ISSUE TITLE
Deprecation warning about ember-getowner-polyfill after upgrading to Ember v2.12.1

### ISSUE THREAD

**Issue by localpcguy** [runspired/smoke-and-mirrors#160]
Got the following deprecation notice after upgrading Ember to v2.12.1 (from v2.9.x).

>DEPRECATION: ember-getowner-polyfill is now a true polyfill. Use Ember.getOwner directly instead of importing from ember-getowner-polyfill

https://github.com/rwjblue/ember-getowner-polyfill/issues/5

Looks like possibly the version of ember-getowner-polyfill just needs to be bumped to the latest version?

**Comment by rwjblue** [comment]
The solution is to remove this line https://github.com/runspired/smoke-and-mirrors/blob/a0747f790d19bea0572c7a875eb4cdcab56f07de/addon/components/vertical-item/component.js#L3 and add:

```js
const { getOwner } = Ember;
```

Then bump the polyfill to the latest 1.x version.
