### ISSUE TITLE
Does this addon still work with latest versions of ember? (2.16+) Getting Uncaught TypeError: Cannot read property 'oldAttrs' of undefined on vertical-collection component

### ISSUE THREAD

**Issue by kjhangiani** [runspired/smoke-and-mirrors#168]
It looks like `vertical-collection` is using the deprecated `attrs` param to `didReceiveAttrs` and throwing an error:

`Uncaught TypeError: Cannot read property 'oldAttrs' of undefined`

```
_didReceiveAttrs: function _didReceiveAttrs(attrs) {
      var oldArray = attrs.oldAttrs && attrs.oldAttrs.content ? attrs.oldAttrs.content.value : false;
      var newArray = attrs.newAttrs && attrs.newAttrs.content ? attrs.newAttrs.content.value : false;

      if (oldArray && newArray && this._changeIsPrepend(oldArray, newArray)) {
```

in the component

Is this addon still supported and/or recommended in modern ember?

**Comment by runspired** [comment]
@kjhangiani we split out the vertical-collection here: https://github.com/html-next/vertical-collection

We will be updating this repo to use that version very soon.

**Comment by runspired** [comment]
Updated.
