### ISSUE TITLE
occlusion-collection: maintaining scroll position during prepend

### ISSUE THREAD

**Issue by aquamme** [runspired/smoke-and-mirrors#27]
There is an edge case that the current logic doesn't handle. If the estimated height of the views to be prepended exceeds the current maximum scrollTop value, that difference is lost. 

For instance, if there is 1500px of content in a 700px viewport, the max scrollTop value is 800px. If the scrollTop is 0px and more content which has a estimated height of 1500px is about to be prepended, the scrollTop is set to 1500px, which exceeds the 800px maximum, resulting in a 700px difference between the final scrollTop and the correct final scrollTop.

A possible fix would be to adjust the scrollTop after the items are inserted instead of before. Any other ideas, @runspired ?

**Comment by runspired** [comment]
I think longterm I want to explore ways to get real heights calculated before insertion happens and then smoothly autogrow.  Short term this sounds like the right change to make.
