### ISSUE TITLE
bower dependencies are not imported correctly

### ISSUE THREAD

**Issue by shime** [runspired/smoke-and-mirrors#34]
I'm getting this in my Ember 1.12.0 app:

```
Path or pattern "bower_components/animation-frame/AnimationFrame.min.js" did not match any files
```

Something weird is happening with `addBowerPackagesToProject` and switching to `addBowerPackageToProject` doesn't help either.

ember-cli/ember-cli-qunit#37

**Comment by runspired** [comment]
This sounds like an `ember-cli` issue?
