### ISSUE TITLE
"component" is undefined for vertical-collection (0.2.2)

### ISSUE THREAD

**Issue by mbrakken** [runspired/smoke-and-mirrors#37]
During `setup` on the vertical-collection, 
```javascript
childForItem: function childForItem(item) {
    var val = get(item, this.get("keyForId"));
    return this.get("_children")[val];
}
```
returns `undefined`, because `this.get("_children") === {}`. I don't see `_children` updated anywhere other than in `_prepareComponent`, where it's set to `{}`, so I'm not sure what's supposed to be in it other than something like `{"keyForIdVal": someRepresentationOfAnObject, ...}`.

From What I've been able to determine, the overall call stack in question is `setup()` --> `_initializeScrollState()` --> `_cycleViews()` --> `_findTopView()` --> `childForItem()`, whereupon it dies.

I'd be happy to try to fix this, although I'm not sure what the end case should be. Should `_children` be ```{keyVal: childComponent, ...}```?

For what it's worth, I'm currently calling vertical collection like this:
```javascript
{{#vertical-collection
     content=discs
     keyForId="id"
     defaultHeight=350
     as |disc|
}}
    {{m-disc-li disc=disc}}
{{/vertical-collection}}
```
Best.

**Comment by runspired** [comment]
ugh, damn I knew there was a reason I'd held off tagging this, go back to 0.2.1 for now, I'll patch with 0.2.3.  0.2.2 was mostly fixes for ember 1.12, I'm only about 2/3rds done with the necessary changes for 1.13 :'(

**Comment by mbrakken** [comment]
No problem. I'll try out that version.

**Comment by runspired** [comment]
@mbrakken there's also some CSS you'll need if you use the default tagNames instead of your own.  Just an FYI consistently most of the bugs I've seen implementing this are CSS related (which, doesn't help that the needed CSS isn't included by default yet).  If you're using the custom tags let me know.

**Comment by mbrakken** [comment]
I think I need to hold out for the next version. I'm working on a new project and am keeping sync with most current versions / betas. 0.2.1 didn't perform with 1.13.4, at least in my use case, and I don't want to step back versions.

If there's anything I can do to help out on 0.2.3, I'm happy to try. Otherwise I'll test it as soon as it's available.

**Comment by runspired** [comment]
Resolved by #new-develop branch.
