### ISSUE TITLE
Scroll whole page?

### ISSUE THREAD

**Issue by eviltrout** [runspired/smoke-and-mirrors#4]
I tried out occlusion-collection and it doesn't seem to work when the whole page is scrolled, like on discourse. It seems that scroll events are not triggered by regular div containers on the page. Additionally, even if the scroll events are triggered, it seems that the viewportTop is wrong?

**Comment by runspired** [comment]
@eviltrout thanks! I've been building this with a focus on scrolled divs.  The additional code to make this work on the body element wouldn't be much, and I'll add the code + a demo later today.  I'm working on `startFromBottom` right now which renders beginning at the bottom if `_scrollPosition` is not set, I believe that is also a discourse need?

**Comment by msounthar** [comment]
This will be great feature for many scenarios, when we can expect this in the release. Thanks.

**Comment by runspired** [comment]
@msounthar the mechanics of this are different from `ember-cloaking` enough that `offsetFixedTopElement` simply isn't needed

There's been substantial headway made, but the short response is I decided to bail on making the scrollable-div portion work on the body element.  While it wouldn't be hard to do so, the better solution is a service that lets any component anywhere on the page be occluded in various ways based on it's distance from the viewport.

You can expect a release with that solution later this week.

**Comment by msounthar** [comment]
That will be great, Thanks!

**Comment by msounthar** [comment]
any update on this will be great!

**Comment by runspired** [comment]
@msounthar all development got delayed while other updates to support glimmer in other portions of our app were done.  We're nearly able to move to Ember 1.13.x+ and ember-data 1.13.x+ which will unlock continued development of smoke-and-mirrors.  Unfortunately until then I just don't have enough hours for anything not immediately needed.

If you have some dev time, I can task out what needs to be done for the next release and you could take a stab at it.

**Comment by msounthar** [comment]
@runspired Its good that you are working on the compatibility  issues as support for future versions of ember is really crucial.I am pretty busy for this month. I will let you know once I get some free time. Thanks!

**Comment by runspired** [comment]
Closing in favor of #46
