### ISSUE TITLE
Issues introduced in 0.3.1 

### ISSUE THREAD

**Issue by aquamme** [runspired/smoke-and-mirrors#43]
In my app `firstVisibleChanged` no longer triggers reliably, and `lastReached` only triggers once. Any subsequent pages aren't loaded. The regression is in commit 5287871773c67f7c9edcf4238ed2c264d59b9554.

Using Ember 1.13.10.

EDIT: Fixed in 0.3.3

**Comment by aquamme** [comment]
`scrollPosition` and `idForFirstItem` have some issues as well. Item visibility state appears to be calculated based on the assumption that the initial scroll position is 0px. This regression was introduced prior to the one I mentioned above. I'm currently looking into this.

**Comment by aquamme** [comment]
It also looks like scroll position is not maintained when prepending.

**Comment by runspired** [comment]
Excepting what's mentioned below, I think these issues have all been resolved  either in 0.3.3 or in the upcoming 0.3.4 release.  Closing in favor of specific tickets.

- Prepending items with dynamic heights doesn't consistently work. #47
