### ISSUE TITLE
Selecting an item in the collection causes the scroll to jump to the top (0.3.6)

### ISSUE THREAD

**Issue by oliverwilkie** [runspired/smoke-and-mirrors#48]
Hi!

When I scroll down my list (using 0.3.6), select a list element, the scrolling jumps back up to the top.

Not clear if this is a bug or just me not configuring it correctly.

See gif below:
![screen capture on 2015-10-23 at 10-04-22](https://cloud.githubusercontent.com/assets/10522493/10699692/9454b278-796d-11e5-8a43-814eb59a5d41.gif)

```
      {{#vertical-collection
      defaultHeight=60
      alwaysUseDefaultHeight=true
      visibleBuffer=2
      useContentProxy=true
      containerHeight=2000
      content=filteredContent
      as |chatParticipant| }}
        {{cvr-chat-participant
        chatParticipant=chatParticipant}}
      {{/vertical-collection}}
```

**Comment by runspired** [comment]
That definitely seems like a bug, what happens under the hood when you select the item?

**Comment by runspired** [comment]
If you are swapping out the contents in a certain way, it may be that you completely empty the array and then refill it with non-stable references to the same objects, in which case the proxy would need a `key` property set.  It defaults to `@identity` but something like `id` would work better for non-stable objects.

**Comment by oliverwilkie** [comment]
Actually it causes the route to change. So in the gif above clicking List item 100. Causes it to move.

`http://localhost:4200/#/message-center/3/messages`

`http://localhost:4200/#/message-center/100/messages`

Is there a way to define an element to scroll to on loading?

**Comment by runspired** [comment]
yes, `itemForId` or `scrollPosition` both can be set to specify where you should start loading.  In your case, since you probably want to preserve the exact granularity of the scroll I'd use `scrollPosition`

**Comment by oliverwilkie** [comment]
Thanks I will take a look at those.

**Comment by oliverwilkie** [comment]
Apologies, our code was at fault. We'd previously been using ember list view and had implemented some event listeners to handle some keyboard shortcuts and they were interfering with this.

**Comment by runspired** [comment]
@oliverwilkie If you care to share exactly what interfered and how I'd be interested to know.  I'm also going to keep this issue open until I land a little more documentation on configuring the collection.
