### ISSUE TITLE
Can't scroll up without scrolling down first

### ISSUE THREAD

**Issue by rlivsey** [runspired/smoke-and-mirrors#53]
Infinite scroll only loads more content above if you scroll up, but as there's nothing above to scroll into at first there's no way to scroll up. In order to load content above, you need to scroll down a little and then up again to kick it into action.

Maybe there should be a small buffer added to the top, then when rendering initially scroll down to the starting point so there's always a small area to scroll upwards.

**Comment by runspired** [comment]
There is a new action hook intended to support this case that will land in `0.3.7`.

The `didMountCollection` action will fire once the component completes it's first render with the following payload.

```
{
   topVisible: { item, index }, 
   bottomVisible: { item, index }
}
```

**Comment by rlivsey** [comment]
Ah cool, so when it mounts we can load the previous set of content and then there'll be somewhere to scroll into. Sounds good to me!

Thanks.

**Comment by runspired** [comment]
:+1:

**Comment by rlivsey** [comment]
:tada:
