### ISSUE TITLE
Files missing from npm package

### ISSUE THREAD

**Issue by aquamme** [runspired/smoke-and-mirrors#6]
It doesn't look like the dependency on the animation-frame package is declared anywhere in package.json or bower.json, so unless it's installed manually, a consuming application will fail to build.

Thanks for your work on this project. There's a lot of very exciting stuff here, and I hope to see and be a part of future iterations.

Sidenote: Is there a reason the project doesn't have a bower.json file?

**Comment by runspired** [comment]
That dependency is in bower.json, which is here: https://github.com/runspired/smoke-and-mirrors/blob/master/bower.json

**Comment by aquamme** [comment]
Hmm, it looks like there are some missing files in the npm package then? '<projectDir>/node_modules/smoke-and-mirrors' contains only these files and folders:

* .idea/
* addon/
* app/
* config/
* docs/
* node_modules/
* .jshintrc
* CHANGELOG.md
* Gruntfile.js
* LICENSE.md
* README.md
* ROADMAP.md
* index.js
* package.json

**Comment by runspired** [comment]
That would be problematic, I'll update that for the next release.  Thanks for the report!

**Comment by aquamme** [comment]
Looks like this has been resolved in 0.2.0-beta.2. Thanks!
