### ISSUE TITLE
Readme cleanup

### ISSUE THREAD

**Issue by aquamme** [runspired/smoke-and-mirrors#7]
* Broken links: 
  * The ones in the guides could be removed
  * The ones in the documentation section could be culled, and replaced with links to the files themselves, since there is good usage info in comments. Alternatively, some doc file generation process could be setup a la Ember core. I haven't used any such tools, but it looks like JSDoc and YUIDoc are common options.
* The animation section could use some elaboration
* I haven't verified it, but is window.requestAnimationFrame being shimmed now by the 'animation-frame' bower package? If so, the 'browser support' section could be updated

I'd be happy to submit a PR for any or all of the above items if you approve, with the exception of the animation section since I don't have the requisite knowledge.

**Comment by runspired** [comment]
Approve of all, would love to set up YUI doc animation. I tried to but didn't like the result I got.  Would prefer something that generates markdown (if that exists).

requestAnimationFrame is shimmed now, browser support is untested but *theoretically* goes back to IE8.  I'd leave it as officially supporting IE9+ as I'll be bringing this up to shape along with Ember 2.0

Ignore the animation section for now.  There are a LOT of things coming in this lib that I simple haven't had time to finish, but basically the idea is to generate a large set of components that utilize occlusion and/or the magicArray.  The animations are there to support the carousel and off-canvas components that are part of this.  I *want* to continue using the liquid-fire transition map approach for them, but the last time I investigated this (a while back) using liquid-fire itself wasn't going to work well enough with some of the other mechanics involved.  I think that's changed, and I'm rather stalling a bit on those to see more of liquid-fire's evolution.  There's talk of making it easy for addons to define their own transitions, which is the main thing needed.
