### ISSUE TITLE
[FEAT] Grid Support

### ISSUE THREAD

**Issue by runspired** [runspired/smoke-and-mirrors#72]
The `vertical-collection` and the upcoming `horizontal-collection` should both support grids.

Currently grid support can be achieved by splitting your content into rows beforehand and treating each row as an individual item (or column).  This degrades the consumer experience by requiring extra work and extra DOM elements to accomplish what a few CSS styles would have given you out of the box.

The `collection` components should support `float`s and `margin`s as well as multiple items per pixel offset.  Going in hand with these changes, the upgrades in #70 will allow use of `float` directly on your content instead of on the `vertical-item` wrappers. 

Can be implemented now:
 - [ ] `_findFirstRenderedComponent` should crawl up the component list after a resolution to check for additional components that should be rendered in case the binary search landed in the middle of a batch of items at a similar offset.
 - [ ] `defaultWidth` needs to be added
 - [ ] `defaultMargin` needs to be added

For later:
 - [ ] Remove `vertical-item` wrappers #70 
 - [ ] The top most and bottom most offset of visible items (not necessarily the first/last item) needs to be used when adjusting the `filler` divs above and below the visible content.

**Comment by NicholasJohn16** [comment]
Is this issue going to be tracked in #98 now or has it been resolved? I subscribed cause I was interested in grid support.

**Comment by runspired** [comment]
@NicholasJohn16 it'll be tracked in the successor to #98 once a release utilizing DOM recycling has been pushed.
