### ISSUE TITLE
Geography.getZones() incorrectly zones divs of same location and size

### ISSUE THREAD

**Issue by kylemellander** [runspired/smoke-and-mirrors#82]
When 2 planets have the same dimensions and locations, getZones fails:

ie. 
`planetA = planetB;`
`var results = planetA.getZones(planetB);`
// expected result is `{zoneX: 0, zoneY: 0, ...}`
but result is `{zoneX: 1, zoneY: 1, ...}`

this bug is from lines 85 and 86 of addon/models/geography.js

because distanceX === planet.height

**Comment by runspired** [comment]
Resolved by https://github.com/runspired/smoke-and-mirrors/commit/64557c69b0cb7b7eb614791bb036d73616ef1c0e
