### ISSUE TITLE
vertical collection and ember-data

### ISSUE THREAD

**Issue by maoamid** [runspired/smoke-and-mirrors#85]
Hi, 
Can someone guid me how to create a simple infinite-scroll with ember-data? 
I receive: Cannot call get with 'content' on an undefined object . It suposed to work with an array of objects only, so I need to create a controller to get data from my model?
May be I do not understand very well how is suposed work. I apreciate some hints

**Comment by runspired** [comment]
Ping me on the #smoke-and-mirrors channel on the Ember Community slack and I'd gladly help out.  From what I've observed, this usually means you've passed it a promise instead of an array.

**Comment by ganesharulanantham** [comment]
same issue

**Comment by dehuszar** [comment]
Same issue as well.

**Comment by localpcguy** [comment]
I was also getting this error, but interestingly enough, not on infinite scroll, but when the browser was resized from desktop down to a mobile size. In the scenario I saw it, I had multiple vertical-collections (2 columns, odd/even) that referenced a single parent for the scrolling div, that stack for mobile. I can provide more info as needed, feel free to hit me up on the Ember Slack in that case.
