### ISSUE TITLE
occlusion-collection rendering issues

### ISSUE THREAD

**Issue by aquamme** [runspired/smoke-and-mirrors#9]
While the infinite-scroll demo works nearly flawlessly, I've come across a few issues with the occlusion-collection which can be reproduced in the DBMon - Occlusion demo. When scrolling, sometimes rows disappear and fail to return until further scroll events are fired, and sometimes the scroll position jumps back to the top of the table.

**Comment by runspired** [comment]
I've noticed that too, the two use the same code base, and I've (largely) concluded that it's simply a factor of how much stress that page is under and how narrow the boundaries for whats visible were set.  I'm using this in a number of different places in our app without the same issue.

I'll leave this open in case someone can offer more insight, but this isn't something that's limited full use thus far.

**Comment by aquamme** [comment]
For anyone else encountering this issue, I've been able to avoid the problem in my app by tweaking the `visibleBuffer`, `invisibleBuffer`, and `cacheBuffer` values.

**Comment by patuku-roy** [comment]
@runspired I have the same problem with @aquamme but I believe this is because my items height are various. I tried to adjust `visibleBuffer` and `invisibleBuffer`. I think almost impossible to achieve by adjust those 2 properties, because after particular scroll position always hide the items. Do you have any idea how to avoid that problem with various items height?

**Comment by runspired** [comment]
@patuku-roy it turns out that the issue there was because of `min-height` not being respected by `tr`s.

**Comment by patuku-roy** [comment]
@runspired sorry for late response, anyway can you point me to valid example how to use the component? maybe I miss something and IMHO the docs a little bit outdated also. The occlusion is worked except above problem.
