### ISSUE TITLE
Should support cases where component is rendered in a container with display:none

### ISSUE THREAD

**Issue by toddjordan** [runspired/smoke-and-mirrors#95]
I have a search component that is hidden in a side panel until you click the search button, and I am using vertical-collection to render results.  Results are not displayed until I resize the window and scroll.  When I hide the panel with visibility:hidden, the list renders fine when shown.  Component should provide a way to re-init/calculate layout when initially rendered as display:none.

**Comment by pzuraq** [comment]
@runspired could potentially be solved with the `ResizeEvent` in [this PR](https://github.com/html-next/vertical-collection/pull/15). Essentially we're going from a non-existent container (`height: 0px;`) to whatever it should be by default, can't think of another hook that would be able to tell it to rerender.

**Comment by runspired** [comment]
Should be fixed by updating to `@html-next/vertical-collection` (now re-exported by this lib)
