### ISSUE TITLE
chore(ember-radar): separate out the radar code and in-viewport mixin/service to a standalone addon

### ISSUE THREAD

**Issue by runspired** [runspired/smoke-and-mirrors#96]
What the title says.

**Comment by runspired** [comment]
@locks were you gonna tackle this? Was that you?  The radar setup in `develop` is now much further along.

**Comment by locks** [comment]
Hey @runspired, it was me, but I was not successful in understanding the code at the time. Should I try again? If you don't want to be held back go ahead!

**Comment by runspired** [comment]
@locks I think it's simpler now.
